Saving a training model into a file using pickle

Solving a ML Problem Consist of 2 steps

Step 1: Training a model using dataset


Step 2: Using the trained model to predict the values of Test set.

Often the training set is huge in gigabytes and hence it is tough to train the model each time hence we can save the train model using using to load it from file on later use

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df=pd.read_csv("/Sem6 Project Prep/ML/files/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [5]:
reg.predict([[3300]])

c:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [6]:
m=reg.coef_
m

array([135.78767123])

In [7]:
c=reg.intercept_
c

180616.43835616432

In [8]:
y=m*3300+c   #x=3300
y

array([628715.75342466])

Now we use Pickle module: It is used for serializing any object in python to a file.

In [9]:
import pickle

In [12]:
with open('/Sem6 Project Prep/ML/files/model_pickle','wb') as f:
    pickle.dump(reg,f)

In [13]:
with open("/Sem6 Project Prep/ML/files/model_pickle",'rb') as f:
    mp=pickle.load(f)

In [15]:
mp.predict([[3300]])

c:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In this way we can load a saved trained modela nd use it any time easily.

We use sklearn joblib to do the same task but it is used more often when we have huge numpy array.

In [18]:
import joblib

In [19]:
joblib.dump(reg,'/Sem6 Project Prep/ML/files/model_joblib')

['/Sem6 Project Prep/ML/files/model_joblib']

In [20]:
mj=joblib.load('/Sem6 Project Prep/ML/files/model_joblib')

In [21]:
mj.predict([[7000]])

c:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1131130.1369863])